version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminakamra
      POSTGRES_DB: nba_record
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

